default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: poda
  password: 12341234
  host: localhost

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: postgresql://postgres:TaEDcjgTfHkKqsfBdoNERzqNevknsaiK@postgres.railway.internal:5432/railway
